const helmetDefectDetails = [
  "Batch,Model & Size Label Missing",
  "Belt edge without stitch",
  "Black Dot",
  "Bond spillage Mark",
  "Buckle not working/Damage",
  "Buckle paint peeloff",
  "Center offset",
  "Coating Dust",
  "Colour & Size mismatch",
  "D- ring without stitching",
  "D-ring Missing",
  "D2 Model mixup",
  "Damage",
  "Damage / Model Mixup",
  "Dent / Damage",
  "Dent & Damage",
  "Double Print",
  "EPS came out",
  "EPS Damage Inprocess",
  "Flashes",
  "Flashes & Thread",
  "Flow Mark",
  "Glue Came Out",
  "Glue spilage on shell",
  "harness bracket rivet tight",
  "Harness foam lamination issue",
  "Harness foam missing",
  "Harness/Ticky model mixup",
  "Improper mesh pasting",
  "Improper Pad Pasting",
  "Improper printing",
  "Improper Visor trims pasting",
  "Inprocess damage",
  "Kaja stitch open",
  "LH & RH Wrong Assembly",
  "loose assembly",
  "Mesh Came Out",
  "Missing",
  "Model Mixup",
  "Open Stitch",
  "Over ironing",
  "paint spilage",
  "PeelOff",
  "Printing issues",
  "Rivet damage",
  "Rivet impression mark on shell",
  "Rivet loose",
  "Rivet missing",
  "Rivet rusting",
  "Rust",
  "scoring mark",
  "Scratches",
  "Shell & EPS between Gap",
  "Shell Damage In Riveting Area",
  "Short & Over Length",
  "Silver streak",
  "Sink Mark",
  "Size label damage & improper stitch",
  "Stitch open & Without Stitching",
  "Stress Mark",
  "Thread uncut",
  "Tickey Center Out",
  "Ticky lamination issue",
  "Washer missing",
  "Without Cleaning",
  "Without Coating",
  "Without Deburring",
  "Without Packing Cover",
  "Without printing",
  "Wrinkles",
  "Wrong Assembly",
  "Wrong position assemble",
  "Wrong position riveting"
];

module.exports = helmetDefectDetails;
